apiVersion: v1
kind: Service
metadata:
  name: streaming-consumer
  labels:
    io.kompose.service: streaming-consumer
spec:
  ports:
    - port: 9999
      targetPort: 8080
      name: consumer-port
  selector:
    io.kompose.service: streaming-consumer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-consumer
  labels:
    app: streaming-consumer
    io.kompose.service: streaming-consumer
spec:
  selector:
    matchLabels:
      app: streaming-consumer
      io.kompose.service: streaming-consumer
  template:
    metadata:
      labels:
        app: streaming-consumer
        io.kompose.service: streaming-consumer
    spec:
      containers:
      - image: docker.io/codeworksio/nginx
        name: streaming-consumer
        ports:
        - containerPort: 8080
          name: consumer-port
        volumeMounts:
        - name: streaming-consumer-claim0
          mountPath: /var/www
      volumes:
      - name: streaming-consumer-claim0
        persistentVolumeClaim:
          claimName: streaming-consumer-claim0
