apiVersion: v1
kind: Service
metadata:
  name: streaming-server
  labels:
    io.kompose.service: streaming-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: server-port
  #type: LoadBalancer
  selector:
    io.kompose.service: streaming-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-server
  labels:
    app: streaming-server
    io.kompose.service: streaming-server
spec:
  selector:
    matchLabels:
      app: streaming-server
      io.kompose.service: streaming-server
  template:
    metadata:
      labels:
        app: streaming-server
        io.kompose.service: streaming-server
    spec:
      containers:
      - image: docker.io/codeworksio/streaming-server
        name: streaming-server
        ports:
        - containerPort: 8080
          name: server-port
        volumeMounts:
        - name: streaming-server-claim0
          mountPath: /var/lib/streaming
      volumes:
      - name: streaming-server-claim0
        persistentVolumeClaim:
          claimName: streaming-server-claim0
